inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/migrate/*.hyrax.rb'
    - 'spec/internal_test_hyku/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/conversions/**/*'
    - 'spec/features/**/*'
    - 'spec/inputs/**/*'
    - 'spec/views/**/*'
