inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/migrate/*.hyrax.rb'
    - 'spec/internal_test_hyku/**/*'
    - 'vendor/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/hyku_addons/engine.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'app/helpers/hyku_addons/multiple_metadata_fields_helper.rb'
    - 'app/models/concerns/hyku_addons/generic_work_overrides.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'app/models/concerns/hyku_addons/generic_work_overrides.rb'
    - 'app/models/concerns/hyku_addons/solr_document_behavior.rb'
    - 'hyku_addons.gemspec'
    - 'lib/hyku_addons/engine.rb'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'app/forms/concerns/hyku_addons/generic_work_form_overrides.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/hyku_addons/multiple_metadata_fields_helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/helpers/hyku_addons/multiple_metadata_fields_helper.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/conversions/**/*'
    - 'spec/features/**/*'
    - 'spec/inputs/**/*'
    - 'spec/views/**/*'

RSpec/ExampleLength:
  Max: 10

Style/SymbolProc:
  Exclude:
    - 'app/models/concerns/hyku_addons/account_behavior.rb'

Style/StructInheritance:
  Enabled: false

Style/MethodMissing:
  Exclude:
    - 'lib/hyku_addons/engine.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/renderers/**/*'