inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/migrate/*.hyrax.rb'
    - 'spec/internal_test_hyku/**/*'
    - 'vendor/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/hyku_addons/generic_work_overrides.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/models/concerns/hyku_addons/generic_work_overrides.rb'
    - 'app/models/concerns/hyku_addons/solr_document_behavior.rb'
    - 'hyku_addons.gemspec'
    - 'lib/hyku_addons/engine.rb'
    - 'spec/**/*.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/conversions/**/*'
    - 'spec/features/**/*'
    - 'spec/inputs/**/*'
    - 'spec/views/**/*'

RSpec/ExampleLength:
  Max: 10

Style/SymbolProc:
  Exclude:
    - 'app/models/concerns/hyku_addons/account_behavior.rb'