inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/migrate/*.hyrax.rb'
    - 'spec/internal_test_hyku/**/*'
    - 'vendor/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/services/bolognese/readers/base_work_reader.rb'
    - 'lib/hyku_addons/engine.rb'

Metrics/LineLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'spec/jobs/register_doi_job_spec.rb'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'app/forms/concerns/hyku_addons/work_form.rb'
    - 'app/helpers/hyku_addons/multiple_metadata_fields_helper.rb'
    - 'app/models/concerns/hyku_addons/generic_work_overrides.rb'
    - 'app/models/concerns/hyku_addons/solr_document_behavior.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'app/models/concerns/hyku_addons/generic_work_overrides.rb'
    - 'app/models/concerns/hyku_addons/solr_document_behavior.rb'
    - 'app/models/concerns/hyku_addons/work_base.rb'
    - 'app/forms/concerns/hyku_addons/collection_form_behavior.rb'
    - 'app/forms/concerns/hyku_addons/work_form.rb'
    - 'app/models/pacific_article.rb'
    - 'app/services/bolognese/writers/ris_writer_behavior.rb'
    - 'hyku_addons.gemspec'
    - 'lib/hyku_addons/engine.rb'
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'app/forms/concerns/hyku_addons/generic_work_form_overrides.rb'
    - 'app/forms/concerns/hyku_addons/work_form.rb'
    - 'app/models/hyku_addons/csv_entry.rb'
    - 'app/services/bolognese/readers/base_work_reader.rb'
    - 'app/services/bolognese/writers/ris_writer_behavior.rb'
    - 'lib/hyku_addons/engine.rb'
    - 'lib/tasks/account.rake'
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/hyku_addons/multiple_metadata_fields_helper.rb'
    - 'lib/hyku_addons/engine.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/helpers/hyku_addons/multiple_metadata_fields_helper.rb'
    - 'lib/hyku_addons/engine.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/forms/concerns/hyku_addons/work_form.rb'
    - 'app/models/hyku_addons/csv_entry.rb'
    - 'app/services/bolognese/writers/ris_writer_behavior.rb'
    - 'lib/hyku_addons/engine.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/conversions/**/*'
    - 'spec/features/**/*'
    - 'spec/inputs/**/*'
    - 'spec/views/**/*'

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/features/**/*'
    - 'spec/requests/api_v1_work_spec.rb'
    - 'spec/services/bolognese/readers/generic_work_reader_spec.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/helpers/work_forms_context.rb'

RSpec/NestedGroups:
  Exclude:
    - 'spec/services/bolognese/readers/generic_work_reader_spec.rb'

Style/SymbolProc:
  Exclude:
    - 'app/models/concerns/hyku_addons/account_behavior.rb'

Style/StructInheritance:
  Enabled: false

Style/MethodMissing:
  Exclude:
    - 'lib/hyku_addons/engine.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/renderers/**/*'

Rails/Date:
  Exclude:
    - 'spec/services/bolognese/readers/generic_work_reader_spec.rb'
