version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
        default: 2.7.1
      bundler_version:
        type: string
        default: 2.1.4
      rails_version:
        type: string
        default: 5.2.4.3

    executor:
      name: 'samvera/ruby_fcrepo_solr_redis_postgres'
      ruby_version: << parameters.ruby_version >>

    parallelism: 4

    environment:
      RAILS_VERSION: << parameters.rails_version >>
      DATABASE_NAME: circle_test
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: postgres
      DATABASE_TEST_NAME: circle_test
      BUNDLE_PATH: vendor/bundle
      COVERALLS_PARALLEL: true
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      RAILS_ENV: test
      RACK_ENV: test
      FCREPO_TEST_PORT: 8080/fcrepo
      SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      CFLAGS: -Wno-error=format-overflow

    steps:
      - samvera/cached_checkout

      - run: git submodule init && git submodule update

      # FIXME: caching is not working
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - samvera/rubocop

      - samvera/install_solr_core:
          solr_config_path: 'spec/internal_test_hyku/solr/config'

      - run: bundle exec rake app:db:create app:db:schema:load app:zookeeper:upload

      - samvera/parallel_rspec

      - store_artifacts:
          path: coverage

      # TODO: Use CodeClimate

workflows:
  ci:
    jobs:
      - bundle_lint_test:
          name: ruby2-7-1
