---
attributes:
  title:
    type: string
    predicate: http://purl.org/dc/terms/title
    multiple: true
    index_keys:
    - title_tesim
    - title_sim
    form:
      required: true
      primary: true
      multiple: false
  alt_title:
    type: string
    predicate: http://purl.org/dc/terms/alternative
    multiple: true
    index_keys:
    - alt_title_tesim
    form:
      required: false
      primary: true
      multiple: true
  creator:
    predicate: http://purl.org/dc/elements/1.1/creator
    multiple: true
    index_keys: []
    form:
      required: true
      primary: true
      multiple: true
  date_published:
    type: string
    predicate: http://purl.org/dc/terms/available
    multiple: false
    index_keys:
    - date_published_tesim
    form:
      required: true
      primary: true
      multiple: false
  abstract:
    type: text
    predicate: http://purl.org/dc/terms/abstract
    multiple: false
    index_keys:
    - abstract_tesim
    form:
      required: true
      primary: true
      multiple: false
  resource_type:
    predicate: http://purl.org/dc/terms/type
    multiple: true
    index_keys: []
    form:
      required: true
      primary: true
      multiple: true
  license:
    predicate: http://purl.org/dc/terms/rights
    multiple: true
    index_keys: []
    form:
      required: true
      primary: true
      multiple: true
  place_of_publication:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/Place
    multiple: true
    index_keys:
    - place_of_publication_tesim
    - place_of_publication_sim
    form:
      required: false
      primary: true
      multiple: true
  language:
    predicate: http://purl.org/dc/elements/1.1/language
    multiple: true
    index_keys: []
    form:
      required: false
      primary: true
      multiple: true
  subject_text:
    type: string
    predicate: http://purl.org/dc/terms/subject
    multiple: true
    index_keys:
    - subject_text_tesim
    form:
      required: false
      primary: true
      multiple: true
  mesh:
    type: string
    predicate: http://purl.org/dc/terms/MESH
    multiple: true
    index_keys:
    - mesh_tesim
    form:
      required: false
      primary: true
      multiple: true
  add_info:
    type: string
    predicate: http://purl.org/ontology/bibo/Note
    multiple: false
    index_keys:
    - add_info_tesim
    form:
      required: false
      primary: true
      multiple: false
  contributor:
    predicate: http://purl.org/dc/elements/1.1/contributor
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
  publisher:
    predicate: http://purl.org/dc/elements/1.1/publisher
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
  source:
    predicate: http://purl.org/dc/terms/source
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
  journal_frequency:
    type: string
    predicate: http://purl.org/dc/terms/Frequency
    multiple: true
    index_keys:
    - journal_frequency_tesim
    form:
      required: false
      primary: false
      multiple: true
  funding_description:
    type: string
    predicate: http://id.loc.gov/vocabulary/relators/spn
    multiple: true
    index_keys:
    - funding_description_tesim
    form:
      required: false
      primary: false
      multiple: true
  citation:
    type: string
    predicate: http://purl.org/dc/terms/references
    multiple: true
    index_keys:
    - citation_tesim
    form:
      required: false
      primary: false
      multiple: true
  table_of_contents:
    type: string
    predicate: http://bibframe.org/vocab/tableOfContents
    multiple: false
    index_keys:
    - table_of_contents_tesim
    form:
      required: false
      primary: false
      multiple: false
  extent:
    type: string
    predicate: http://purl.org/dc/terms/extent
    multiple: true
    index_keys:
    - extent_tesim
    form:
      required: false
      primary: false
      multiple: true
  medium:
    type: string
    predicate: http://purl.org/dc/terms/medium
    multiple: true
    index_keys:
    - medium_tesim
    form:
      required: false
      primary: false
      multiple: true
  library_of_congress_classification:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/ClassificationLcc
    multiple: true
    index_keys:
    - library_of_congress_classification_tesim
    - library_of_congress_classification_sim
    form:
      required: false
      primary: false
      multiple: true


  related_url:
    predicate: http://www.w3.org/2000/01/rdf-schema#seeAlso
    multiple: true
    index_keys: []
  rights_statement:
    predicate: http://www.europeana.eu/schemas/edm/rights
    multiple: true
    index_keys: []


  official_link:
    type: string
    predicate: http://schema.org/url
    multiple: false
    index_keys:
    - official_link_tesim
    form:
      required: false
      primary: false
      multiple: false
  institution:
    type: string
    predicate: http://www.w3.org/ns/org#organization
    multiple: true
    index_keys:
    - institution_tesim
    - institution_sim
    form:
      required: false
      primary: false
      multiple: true
  org_unit:
    type: string
    predicate: http://www.w3.org/ns/org#OrganizationalUnit
    multiple: true
    index_keys:
    - org_unit_tesim
    form:
      required: false
      primary: false
      multiple: true
  funder:
    type: string
    predicate: http://id.loc.gov/vocabulary/relators/fnd
    multiple: true
    index_keys:
    - funder_tesim
    form:
      required: false
      primary: false
      multiple: true
  fndr_project_ref:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/awards
    multiple: true
    index_keys:
    - fndr_project_ref_tesim
    form:
      required: false
      primary: false
      multiple: true
  date_accepted:
    type: string
    predicate: http://purl.org/dc/terms/dateAccepted
    multiple: false
    index_keys:
    - date_accepted_tesim
    form:
      required: false
      primary: false
      multiple: false
  date_submitted:
    type: string
    predicate: http://bibframe.org/vocab/originDate
    multiple: false
    index_keys:
    - date_submitted_tesim
    form:
      required: false
      primary: false
      multiple: false
  project_name:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/CollectiveTitle
    multiple: true
    index_keys:
    - project_name_tesim
    form:
      required: false
      primary: false
      multiple: true
  rights_holder:
    type: string
    predicate: http://purl.org/dc/terms/rightsHolder
    multiple: true
    index_keys:
    - rights_holder_tesim
    form:
      required: false
      primary: false
      multiple: true
  alternate_identifier:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/Local
    multiple: true
    index_keys:
    - alternate_identifier_tesim
    form:
      required: false
      primary: false
      multiple: true
  related_identifier:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/identifiedBy
    multiple: true
    index_keys:
    - related_identifier_tesim
    form:
      required: false
      primary: false
      multiple: true
  dewey:
    type: string
    predicate: http://schema.org/CategoryCode
    multiple: false
    index_keys:
    - dewey_tesim
    form:
      required: false
      primary: false
      multiple: false
  note:
    type: string
    predicate: http://www.loc.gov/mods/rdf/v1#note
    multiple: true
    index_keys:
    - note_tesim
    form:
      required: false
      primary: false
      multiple: true
  source_identifier:
    type: string
    predicate: http://www.w3.org/ns/prov#wasDerivedFrom
    multiple: false
    index_keys:
    - source_identifier_tesim
    form:
      required: false
      primary: false
      multiple: false
  location:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/physicalLocation
    multiple: false
    index_keys:
    - location_tesim
    - location_sim
    form:
      required: false
      primary: false
      multiple: false
  label:
    predicate: info:fedora/fedora-system:def/model#downloadFilename
    multiple: false
    index_keys: []
    form:
      required: false
      primary: false
      multiple: false
  relative_path:
    predicate: http://scholarsphere.psu.edu/ns#relativePath
    multiple: false
    index_keys: []
    form:
      required: false
      primary: false
      multiple: false
  import_url:
    predicate: http://scholarsphere.psu.edu/ns#importUrl
    multiple: false
    index_keys: []
    form:
      required: false
      primary: false
      multiple: false
  description:
    predicate: http://purl.org/dc/elements/1.1/description
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
  keyword:
    predicate: http://purl.org/dc/elements/1.1/relation
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
  date_created:
    predicate: http://purl.org/dc/terms/created
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
  subject:
    predicate: http://purl.org/dc/elements/1.1/subject
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
  identifier:
    predicate: http://purl.org/dc/terms/identifier
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
  based_near:
    predicate: http://xmlns.com/foaf/0.1/based_near
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
  bibliographic_citation:
    predicate: http://purl.org/dc/terms/bibliographicCitation
    multiple: true
    index_keys: []
    form:
      required: false
      primary: false
      multiple: true
